---
- name: Install angr dependencies
  apt:
    apt:
      - python-dev
      - libffi-dev
      - build-essential
    state: present
  become: yes

- name: get angr
  pip:
    name: angr
  become: yes
